---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  encrypted_data_bag_secret_key_path: test/integration/data_bags/encrypted_data_bag_secret
  data_bags_path: test/integration/data_bags

platforms:
  - name: centos-6.4

suites:
  - name: default
    run_list:
      - recipe[awesome_customers::default]
    attributes:
